name: l10n
description: "A Translation related package."
version: 0.0.1
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
