name: core
description: Core module package."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  auto_route: ^10.1.0+1
  config:
    path: ../../shared/config
  connectivity_plus: ^6.1.4
  dependencies:
    path: ../../shared/dependencies
  device_info_plus: ^11.4.0
  dio_cache_interceptor: ^4.0.3
  dio_smart_retry: ^7.0.1
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_secure_storage: ^9.2.4
  hive: ^2.2.3
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3
  talker: ^4.8.3
  talker_dio_logger: ^4.8.3
  talker_flutter: ^4.8.3

dev_dependencies:
  auto_route_generator: ^10.2.3
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  very_good_analysis: ^9.0.0
