name: {{appName.snakeCase()}}
description: {{appName.pascalCase()}} App Template

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  {{#useAuth}}
  auth:
    path: ../../modules/auth
  {{/useAuth}}
  auto_route: ^10.1.0+1
  config:
    path: ../../shared/config
  core:
    path: ../../packages/core
  cupertino_icons: ^1.0.8
  dependencies:
    path: ../../shared/dependencies
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  settings:
    path: ../../modules/settings
  super_banners: ^0.0.1
  ui_kit:
    path: ../../packages/ui_kit
  visibility_detector: ^0.4.0+2

dev_dependencies:
  auto_route_generator: ^10.2.3
  build_runner: ^2.4.15
  flutter_flavorizr: ^2.4.1
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  path: ^1.9.1
  process_run: ^1.2.4
  retrofit_generator: ^9.2.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/l10n/
    - assets/launcher_icon/
