targets:
  $default:
    builders:
      flutter_gen_runner: # or flutter_gen
        options:
          output: lib/src/gen/ # Optional (default: lib/gen/)
          line_length: 80 # Optional (default: 80)

          # Optional
          integrations:
            image: true
            flutter_svg: true
            rive: true
            lottie: true
