name: ui_kit
description: "UI-Kit"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  cached_network_image: ^3.4.1
  dependencies:
    path: ../../shared/dependencies
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen: ^5.10.0
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
